{{- /* "chezmoi" is present as work around for https://github.com/twpayne/chezmoi/discussions/1724 */ -}}
{{- $cache := dict "chezmoi" .chezmoi -}}

{{- template "read-versions-and-revisions-cache" $cache -}}

".config/base16-shell":
  type: archive
  url: "https://github.com/chriskempson/base16-shell/archive/master.tar.gz"
  stripComponents: 1
  exact: true

"{{ joinPath .fonts_dir .terminalFont.filename }}":
  type: file
  url: "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/SourceCodePro/Regular/SauceCodeProNerdFontMono-Regular.ttf"  

".local/bin/direnv":
  type: file
  url: "https://github.com/direnv/direnv/releases/download/v2.32.3/direnv.linux-{{ .chezmoi.arch }}"
  executable: true

".local/bin/fzf":
  type: file
  url: "https://github.com/junegunn/fzf/releases/download/0.41.1/fzf-0.41.1-linux_{{ .chezmoi.arch }}.tar.gz"
  filter:
    command: tar
    args: ["-x", "-z", "-O", "fzf"]
  executable: true

{{- template "save-versions-and-revisions-cache" $cache -}}