#!/bin/bash

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#nvm use --lts
# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/boonheng/.lmstudio/bin"
# End of LM Studio CLI section


[ -f ~/.fzf.bash ] && source ~/.fzf.bash
